project:
  type: book

lang: de
book:
    title: "In Arbeit!! - HWE-Skript"
    author: "Leopold GÃ¶tsch"
    date: today
    chapters:
    - index.qmd
    - part: 3. Jahrgang
      chapters:
        - Transistoren/01_Transistoren.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    default-image-extension: svg
#  pdf:
#    documentclass: scrreprt
#    default-image-extension: pdf
  docx:
    toc: true
    number-sections: true

#downloads: [pdf]
sidebar:
    pinned: true
    
execute:
    echo: false
    output: true
    
 


